package heuristics

import (
	"math"
	"regexp"
	"strings"

	"github.com/JAugusto42/sandtrap/internal/analyzer"
	"github.com/JAugusto42/sandtrap/internal/registry"
)

// Obfuscation detects heavily obfuscated payloads. The Mini Shai-Hulud
// packages shipped "heavily obfuscated payloads designed to execute during
// installation or import" — this rule targets those construction techniques
// rather than any specific sample.
type Obfuscation struct{}

func (Obfuscation) ID() string { return "obfuscation" }

var (
	// Executors: primitives that RUN code. These are what turn encoded
	// content into a payload. String.fromCharCode is deliberately excluded
	// (encoding utility, the biggest FP source: prettier's flow parser,
	// dart2js output, highlighters).
	reJSExec = regexp.MustCompile(
		`(?i)\beval\s*\(|new\s+Function\s*\(|Function\s*\(\s*["'\x60]`)
	rePyExec = regexp.MustCompile(
		`(?i)\bexec\s*\(|\beval\s*\(|__import__\s*\(|marshal\.loads`)
	// Decoders: turn blobs into bytes/strings. Benign on their own (data
	// tables, wasm, sourcemaps); suspicious only when an executor coexists.
	reJSDecode = regexp.MustCompile(
		`(?i)\batob\s*\(|Buffer\.from\s*\([^)]*,\s*['"]base64['"]`)
	rePyDecode = regexp.MustCompile(
		`(?i)base64\.b(64|32|16)decode|zlib\.decompress`)
	// Long encoded blobs: base64 (>200 chars) or hex escape floods.
	reB64Blob = regexp.MustCompile(`[A-Za-z0-9+/=]{200,}`)
	reHexFld  = regexp.MustCompile(`(\\x[0-9a-fA-F]{2}){24,}`)
	// Identifier mangling from common JS obfuscators (_0x prefixed vars).
	reHexIdent = regexp.MustCompile(`\b_0x[0-9a-f]{4,}\b`)
	// Inline sourcemaps and data-URIs embed huge base64 runs in virtually
	// all bundled JS (fonts, images, wasm). Those are browser-consumed
	// assets, not payload staging — droppers embed naked blobs they can
	// hand to a decoder. Strip both before analysis.
	reSourceMap = regexp.MustCompile(`(?m)^//[#@]\s*sourceMappingURL=data:[^\n]*$`)
	reDataURI   = regexp.MustCompile(`data:[a-zA-Z0-9.+/-]+;base64,[A-Za-z0-9+/=]+`)
	// Compiler banners: dart2js, protoc, babel, wasm-bindgen etc. announce
	// themselves. Machine output legitimately trips pattern rules, so the
	// obfuscation rule skips it; behavior rules (exfiltration, credential
	// access) still inspect these files — those don't depend on style.
	reGenBanner = regexp.MustCompile(`(?i)generated by|do not edit|autogenerated|auto-generated`)
)

func (Obfuscation) Check(a *registry.Artifact) []analyzer.Finding {
	var out []analyzer.Finding
	for _, f := range a.Files {
		if !isCodeFile(f.Path) {
			continue
		}
		content := reDataURI.ReplaceAllString(
			reSourceMap.ReplaceAllString(string(f.Content), ""), "")

		// Announced machine output: obfuscation-style rules don't apply.
		// 8 KiB window: dart2js and friends put the banner after a long
		// license/loader preamble.
		head := content
		if len(head) > 8192 {
			head = head[:8192]
		}
		if reGenBanner.MatchString(head) {
			continue
		}

		var execHits, decHits int
		switch {
		case isJSFile(f.Path):
			execHits = len(reJSExec.FindAllStringIndex(content, 6))
			decHits = len(reJSDecode.FindAllStringIndex(content, 6))
		case isPyFile(f.Path):
			execHits = len(rePyExec.FindAllStringIndex(content, 6))
			decHits = len(rePyDecode.FindAllStringIndex(content, 6))
		}
		hexIdents := 0
		if isJSFile(f.Path) {
			hexIdents = len(reHexIdent.FindAllStringIndex(content, 40))
		}
		blob := reB64Blob.FindString(content)
		// Base64 of real binary data statistically always contains '+' or
		// '/' within 200 chars; pure-alphanumeric runs are minified
		// identifiers, hashes or hex — not encoded payloads.
		if blob != "" && !strings.ContainsAny(blob, "+/") {
			blob = ""
		}
		hexFlood := reHexFld.MatchString(content)
		entropy := avgLineEntropy(content)

		// Categories are DISTINCT techniques; signals measure intensity.
		// The core semantic: decoders and blobs are only suspicious when an
		// executor can run what they produce. atob(dataTable) is how
		// calendars ship ephemeris data and how webpack inlines wasm;
		// eval(atob(blob)) is how Mini Shai-Hulud detonates.
		signals, categories := 0, 0
		if execHits >= 2 {
			signals += 2
			categories++
		} else if execHits == 1 {
			signals++
			categories++
		}
		if decHits >= 1 && execHits >= 1 { // decode feeding execution
			signals += 2
			categories++
		}
		if blob != "" {
			if execHits >= 1 || decHits >= 1 {
				signals++
				categories++
			} else {
				signals++ // inert blob: intensity only, not a technique
			}
		}
		if hexIdents >= 20 {
			signals += 2
			categories++
		}
		if hexFlood {
			signals += 2
			categories++
		}
		if entropy > 5.3 && len(content) > 512 {
			signals++
			categories++
		}
		if categories < 2 {
			continue
		}
		// Payload gate: a dropper carries its payload (encoded blob / hex
		// flood) or fetches it (covered by the exfiltration rule). Bare
		// primitives with no encoded content — code generators like
		// webpack's runtime templates — need more technique diversity
		// before they are worth a human's attention.
		hasPayload := blob != "" || hexFlood
		if !hasPayload && categories < 3 {
			continue
		}

		// Minified bundles and unannounced compiler output: bundlers
		// legitimately co-locate everything (inlined lodash Function
		// calls, wasm shipped as naked base64 — es-module-lexer inside
		// vite). The separator from real malware is the OBFUSCATOR
		// fingerprint: minifiers emit short identifiers (a, b, c), while
		// javascript-obfuscator — the tool actual campaigns use — emits
		// _0x-mangled names and hex-escape floods. Demand that fingerprint
		// here; hand-packed droppers in dist/ are still covered by the
		// exfiltration and credential rules, and by diff mode (roadmap).
		if isMinifiedPath(f.Path) || looksGenerated(content) {
			if hexIdents < 20 && !hexFlood {
				continue
			}
			if signals < 4 {
				continue
			}
		}

		switch {
		case signals >= 4 && hasPayload:
			out = append(out, analyzer.Finding{
				RuleID: "obfuscation", Severity: adjustForTestPath(analyzer.SevCritical, f.Path),
				Title:  "heavily obfuscated executable payload",
				Detail: "Multiple stacked obfuscation techniques (dynamic eval + encoded blobs + mangled identifiers/high entropy). Legitimate source does not combine these; recent npm/PyPI campaigns ship payloads exactly like this.",
				File:   f.Path, Evidence: truncate(firstMatchContext(content, reJSExec, rePyExec, reJSDecode, reB64Blob), 120),
			})
		case signals >= 4, signals == 3 && hasPayload:
			out = append(out, analyzer.Finding{
				RuleID: "obfuscation", Severity: adjustForTestPath(analyzer.SevHigh, f.Path),
				Title:  "strong obfuscation indicators",
				Detail: "Dynamic code evaluation combined with encoded content. Review this file before trusting the package.",
				File:   f.Path, Evidence: truncate(firstMatchContext(content, reJSExec, rePyExec, reJSDecode, reB64Blob), 120),
			})
		case signals >= 2 && !isMinifiedPath(f.Path):
			out = append(out, analyzer.Finding{
				RuleID: "obfuscation", Severity: adjustForTestPath(analyzer.SevMedium, f.Path),
				Title:  "possible obfuscation",
				Detail: "Two independent obfuscation signals in a non-minified source file.",
				File:   f.Path,
			})
		}
	}
	return out
}

func isCodeFile(p string) bool {
	switch ext(p) {
	case ".js", ".mjs", ".cjs", ".ts", ".jsx", ".tsx", ".py", ".sh", ".cmd", ".ps1", ".rb":
		return true
	}
	return false
}
func isJSFile(p string) bool {
	switch ext(p) {
	case ".js", ".mjs", ".cjs", ".ts", ".jsx", ".tsx":
		return true
	}
	return false
}
func isPyFile(p string) bool { return ext(p) == ".py" }
func isMinifiedPath(p string) bool {
	for _, seg := range []string{".min.", "/dist/", "bundle", "/vendor/", "/umd/", ".umd.", ".dart.js", "compiled", "/out/", "lcov-report/"} {
		if strings.Contains(p, seg) {
			return true
		}
	}
	return strings.HasPrefix(p, "dist/") || strings.HasPrefix(p, "vendor/") || strings.HasPrefix(p, "out/")
}

// looksGenerated detects compiler/bundler output by shape: machine-written
// JS (dart2js, webpack, terser) packs code into very long lines, while
// hand-written source rarely exceeds a few hundred columns.
func looksGenerated(content string) bool {
	if len(content) < 2048 {
		return false
	}
	longLines, checked := 0, 0
	for _, line := range strings.SplitN(content, "\n", 60) {
		checked++
		if len(line) > 1000 {
			longLines++
		}
	}
	if checked == 0 {
		return false
	}
	// A single enormous line (fully minified) or a dense cluster of them.
	return longLines*4 >= checked || (checked <= 3 && longLines >= 1)
}
func ext(p string) string {
	if i := strings.LastIndexByte(p, '.'); i >= 0 {
		return strings.ToLower(p[i:])
	}
	return ""
}

// avgLineEntropy computes mean Shannon entropy of non-trivial lines; encrypted
// or packed payloads sit well above typical source (~4.2–4.8 bits/char).
func avgLineEntropy(s string) float64 {
	lines := strings.Split(s, "\n")
	var sum float64
	var n int
	for _, l := range lines {
		if len(l) < 40 {
			continue
		}
		sum += shannon(l)
		n++
		if n >= 400 { // sampling cap for big files
			break
		}
	}
	if n == 0 {
		return 0
	}
	return sum / float64(n)
}

func shannon(s string) float64 {
	var freq [256]int
	for i := 0; i < len(s); i++ {
		freq[s[i]]++
	}
	var h float64
	l := float64(len(s))
	for _, c := range freq {
		if c == 0 {
			continue
		}
		p := float64(c) / l
		h -= p * math.Log2(p)
	}
	return h
}

func firstMatchContext(content string, res ...*regexp.Regexp) string {
	for _, re := range res {
		if loc := re.FindStringIndex(content); loc != nil {
			start := loc[0]
			end := start + 100
			if end > len(content) {
				end = len(content)
			}
			return content[start:end]
		}
	}
	return ""
}
