package lockfile

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/JAugusto42/sandtrap/internal/analyzer"
)

func write(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestDiscoverNPMLockV3(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "package-lock.json", `{
	  "lockfileVersion": 3,
	  "packages": {
	    "": {"name": "myapp", "version": "1.0.0"},
	    "node_modules/axios": {"version": "1.6.0"},
	    "node_modules/@scope/pkg": {"version": "2.0.0"},
	    "node_modules/a/node_modules/b": {"version": "3.0.0"},
	    "node_modules/linked": {"version": "9.9.9", "link": true}
	  }
	}`)
	pkgs, files, err := Discover(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || len(pkgs) != 3 {
		t.Fatalf("want 3 pkgs from 1 file, got %d pkgs %v", len(pkgs), files)
	}
	want := map[string]string{"axios": "1.6.0", "@scope/pkg": "2.0.0", "b": "3.0.0"}
	for _, p := range pkgs {
		if p.Ecosystem != analyzer.NPM {
			t.Fatalf("wrong ecosystem: %v", p)
		}
		if want[p.Name] != p.Version {
			t.Fatalf("unexpected package %v", p)
		}
	}
}

func TestDiscoverRequirements(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "requirements.txt", `
# comment
requests==2.31.0
flask [async] == 3.0.0
-r other.txt
unpinned>=1.0
`)
	pkgs, _, err := Discover(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 2 {
		t.Fatalf("want 2 pinned pkgs, got %v", pkgs)
	}
}

func TestDiscoverEmpty(t *testing.T) {
	pkgs, files, err := Discover(t.TempDir())
	if err != nil || len(pkgs) != 0 || len(files) != 0 {
		t.Fatalf("empty dir: pkgs=%v files=%v err=%v", pkgs, files, err)
	}
}

func TestParseYarnClassic(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "yarn.lock", `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.22.0":
  version "7.22.13"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.22.13.tgz"
  integrity sha512-xxx

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

"string-width-cjs@npm:string-width@^4.2.0":
  version "4.2.3"
  resolved "https://registry.yarnpkg.com/string-width/-/string-width-4.2.3.tgz"
`)
	pkgs, files, err := Discover(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || len(pkgs) != 3 {
		t.Fatalf("want 3 pkgs, got %v (files %v)", pkgs, files)
	}
	want := map[string]string{"@babel/code-frame": "7.22.13", "lodash": "4.17.21", "string-width": "4.2.3"}
	for _, p := range pkgs {
		if want[p.Name] != p.Version || p.Ecosystem != analyzer.NPM {
			t.Fatalf("unexpected %v", p)
		}
	}
}

func TestParseYarnBerry(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "yarn.lock", `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"@scope/pkg@npm:^2.0.0":
  version: 2.3.4
  resolution: "@scope/pkg@npm:2.3.4"

"myapp@workspace:.":
  version: 0.0.0-use.local
  resolution: "myapp@workspace:."

"patched-dep@patch:patched-dep@npm%3A1.0.0#~/.yarn/patches/x.patch":
  version: 1.0.0
  resolution: "patched-dep@patch:patched-dep@npm%3A1.0.0#~/.yarn/patches/x.patch::version=1.0.0"

"axios@npm:^1.6.0":
  version: 1.6.8
  resolution: "axios@npm:1.6.8"
`)
	pkgs, _, err := Discover(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{"@scope/pkg": "2.3.4", "axios": "1.6.8"}
	if len(pkgs) != 2 {
		t.Fatalf("want 2 registry pkgs (workspace+patch skipped), got %v", pkgs)
	}
	for _, p := range pkgs {
		if want[p.Name] != p.Version {
			t.Fatalf("unexpected %v", p)
		}
	}
}
